Patchy_dense_injections = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\patchy\patch_injections_dense_6days\Patchy_dense_injections_6days.mat');
Patchy_dense_injections_div2 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\patchy\patch_infections_dense_6days_div2\patch_infections_dense_6days_div2.mat');
Patchy_dense_injections_div10 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\patchy\patch_injections_dense_6days_div10\patch_infections_dense_6days_div10.mat');
Patchy_dense_injections_div100 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\patchy\patch_injections_dense_6days_div100\patch_infections_dense_6days_div100.mat');
Patchy_dense_injections_x2 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\patchy\patch_infections_dense_6days_x2\patch_infections_dense_6days_x2.mat');
Patchy_dense_injections_x10 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\patchy\patch_infections_dense_6days_x10\patch_infections_dense_6days_x10.mat');

colmap = [102,194,165
252,141,98
141,160,203
231,138,195
166,216,84]/255;

figure
hold on 
plot(Patchy_dense_injections.live_cells/Patchy_dense_injections.live_cells(1)*100,'k--','LineWidth',2)
plot(Patchy_dense_injections_div2.live_cells/Patchy_dense_injections.live_cells(1)*100,'Color',colmap(1,:),'LineWidth',2)
plot(Patchy_dense_injections_div10.live_cells/Patchy_dense_injections.live_cells(1)*100,'Color',colmap(2,:),'LineWidth',2)
plot(Patchy_dense_injections_div100.live_cells/Patchy_dense_injections.live_cells(1)*100,'Color',colmap(3,:),'LineWidth',2)
plot(Patchy_dense_injections_x2.live_cells/Patchy_dense_injections.live_cells(1)*100,'Color',colmap(4,:),'LineWidth',2)
plot(Patchy_dense_injections_x10.live_cells/Patchy_dense_injections.live_cells(1)*100,'Color',colmap(5,:),'LineWidth',2)
legend('Original','V0/2','V0/10','V0/100','V0\times 2','V0\times 10')
xlabel('Time (days)')
ylabel('% GBM cells (uninfected + infected)')
set(gca,'FontSize',19)
set(gca,'XTick',[0 24 48 72],'XTickLabels',{'0','2','4','6'})  
xlim([0 72])


figure
hold on 
bar([Patchy_dense_injections_div100.live_cells(36),...
    Patchy_dense_injections_div10.live_cells(36),...
    Patchy_dense_injections_div2.live_cells(36),...
    Patchy_dense_injections.live_cells(36),...
    Patchy_dense_injections_x2.live_cells(36),...
    Patchy_dense_injections_x10.live_cells(36);...
    Patchy_dense_injections_div100.live_cells(72)...
    Patchy_dense_injections_div10.live_cells(72),...
    Patchy_dense_injections_div2.live_cells(72),...
    Patchy_dense_injections.live_cells(72),...
    Patchy_dense_injections_x2.live_cells(72),...
    Patchy_dense_injections_x10.live_cells(72)])
ylabel('% GBM cells (uninfected + infected)')
set(gca,'FontSize',19)
set(gca,'XTick',[1 2],'XTickLabels',{'3 days','6 days'})
legend('V0/100','V0/10','V0/2','Original','V0\times 2','V0\times 10')

figure
hold on
yyaxis right
plot([7.12/100,7.12/10,7.12/2,7.12,7.12*2,7.12*10],[Patchy_dense_injections_div100.live_cells(36),...
    Patchy_dense_injections_div10.live_cells(36),...
    Patchy_dense_injections_div2.live_cells(36),...
    Patchy_dense_injections.live_cells(36),...
    Patchy_dense_injections_x2.live_cells(36),...
    Patchy_dense_injections_x10.live_cells(36)],'o-','LineWidth',2)
ylabel('% GBM cells (uninfected + infected) at 3 days')
yyaxis left
plot([7.12/100, 7.12/10,7.12/2,7.12,7.12*2,7.12*10],[Patchy_dense_injections_div100.live_cells(72),...
    Patchy_dense_injections_div10.live_cells(72),...
    Patchy_dense_injections_div2.live_cells(72),...
    Patchy_dense_injections.live_cells(72),...
    Patchy_dense_injections_x2.live_cells(72),...
    Patchy_dense_injections_x10.live_cells(72)],'o-','LineWidth',2)
xlabel('Initial dosage (virions/\mu m^3)')
ylabel('% GBM cells (uninfected + infected) at 6 days')
%set(gca,'xscale','log')
set(gca,'FontSize',19)



figure
hold on
yyaxis left
plot([1/100,1/10,1/2,1,2,10],[Patchy_dense_injections_div100.live_cells(36),...
    Patchy_dense_injections_div10.live_cells(36),...
    Patchy_dense_injections_div2.live_cells(36),...
    Patchy_dense_injections.live_cells(36),...
    Patchy_dense_injections_x2.live_cells(36),...
    Patchy_dense_injections_x10.live_cells(36)],'o-','LineWidth',2)
ylabel('% GBM cells (uninfected + infected) at 3 days')
yyaxis right
plot([1/100,1/10,1/2,1,2,10],[Patchy_dense_injections_div100.live_cells(72),...
    Patchy_dense_injections_div10.live_cells(72),...
    Patchy_dense_injections_div2.live_cells(72),...
    Patchy_dense_injections.live_cells(72),...
    Patchy_dense_injections_x2.live_cells(72),...
    Patchy_dense_injections_x10.live_cells(72)],'o-','LineWidth',2)
xlabel('Initial dosage (virions/\mu m^3)')
ylabel('% GBM cells (uninfected + infected) at 6 days')
%set(gca,'xscale','log')
set(gca,'FontSize',19)



