dense_homogeneous_us_0 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_0\dense_homogeneous_us_0.mat');
dense_homogeneous_us_0point00005 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_0point00005\dense_homogeneous_us_000005.mat');
dense_homogeneous_us_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_0point0001\dense_homogeneous_us_0point0001.mat');
dense_homogeneous_us_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_0point001\dense_homogeneous_us_0point001.mat');
dense_homogeneous_us_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_0point01\dense_homogeneous_us_0point01.mat');
dense_homogeneous_us_0point1 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_0point1\dense_homogeneous_us_0point1.mat');
dense_homogeneous_us_1 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_1\dense_homogeneous_us_1.mat');
dense_homogeneous_us_1point5 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_1point5\dense_homogeneous_us_1point5.mat');
dense_homogeneous_us_2 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_2\dense_homogeneous_us_2.mat');

colmap = [255,255,204
199,233,180
127,205,187
65,182,196
29,145,192
34,94,168
12,44,132]/255;

dense_initial_cell_number = dense_homogeneous_us_0.live_cells(1);

figure
hold on 
plot(dense_homogeneous_us_0.live_cells/dense_initial_cell_number*100,'Color',colmap(1,:),'LineWidth',1)
plot(dense_homogeneous_us_0point00005.live_cells/dense_initial_cell_number*100,'Color',colmap(2,:),'LineWidth',1)
plot(dense_homogeneous_us_0point0001.live_cells/dense_initial_cell_number*100,'Color',colmap(3,:),'LineWidth',1)
plot(dense_homogeneous_us_0point001.live_cells/dense_initial_cell_number*100,'Color',colmap(4,:),'LineWidth',1)
plot(dense_homogeneous_us_0point01.live_cells/dense_initial_cell_number*100,'Color',colmap(5,:),'LineWidth',1)
plot(dense_homogeneous_us_0point1.live_cells/dense_initial_cell_number*100,'Color',colmap(6,:),'LineWidth',1)
plot(dense_homogeneous_us_1.live_cells/dense_initial_cell_number*100,'Color',colmap(6,:),'LineWidth',1)
legend('u_s = 0','u_s = 0.00005','u_s = 0.0001','u_s = 0.001','u_s = 0.01','u_s = 0.1','u_s = 1')


figure
hold on 
plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1],[dense_homogeneous_us_0.live_cells(end),...
    dense_homogeneous_us_0point00005.live_cells(end),...
    dense_homogeneous_us_0point0001.live_cells(end),...
    dense_homogeneous_us_0point001.live_cells(end),...
    dense_homogeneous_us_0point01.live_cells(end),...
    dense_homogeneous_us_0point1.live_cells(end),...
    dense_homogeneous_us_1.live_cells(end)]/dense_initial_cell_number*100,':','LineWidth',2)
plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1, 1.5,2],[dense_homogeneous_us_0.live_cells(end),...
    dense_homogeneous_us_0point00005.live_cells(end),...
    dense_homogeneous_us_0point0001.live_cells(end),...
    dense_homogeneous_us_0point001.live_cells(end),...
    dense_homogeneous_us_0point01.live_cells(end),...
    dense_homogeneous_us_0point1.live_cells(end),...
    dense_homogeneous_us_1.live_cells(end),...
    dense_homogeneous_us_1point5.live_cells(end),...
    dense_homogeneous_us_2.live_cells(end)]/dense_initial_cell_number*100,'o','LineWidth',8,'MarkerSize',7)
set(gca,'xscale','log')

figure
hold on 
b = bar([dense_homogeneous_us_0.infiltration(3,:);...
    dense_homogeneous_us_0point00005.infiltration(3,:);...
    dense_homogeneous_us_0point0001.infiltration(3,:);...
    dense_homogeneous_us_0point001.infiltration(3,:);...
    dense_homogeneous_us_0point01.infiltration(3,:);...
    dense_homogeneous_us_0point1.infiltration(3,:);...
    dense_homogeneous_us_1.infiltration(3,:)]','FaceColor','flat','EdgeColor',[0.9 0.9 0.9]);
b(1).CData = colmap(1,:);
b(2).CData = colmap(2,:);
b(3).CData = colmap(3,:);
b(4).CData = colmap(4,:);
b(5).CData = colmap(5,:);
b(6).CData = colmap(6,:);
b(7).CData = colmap(7,:);
set(gca,'FontSize',18)
xlim([0 12])
ylabel('Total virions')
xlabel('\mu m from periphery')
set(gca,'Xtick',linspace(1,16,16),'Xticklabel',{'0','50','100','150','200','250','300','350','400','450','500','550','600','650','700','750'})
legend('u_s = 0','u_s = 0.00005','u_s = 0.0001','u_s = 0.001','u_s = 0.01','u_s = 0.1','u_s = 1')
colormap(colmap)
c = colorbar;
set(c,'Ticks',linspace(0,1,7),'TickLabels',{'0','0.00005','0.0001','0.001','0.01','0.1','1'})


%% ------------------------------------------------------------------------------------------------------------
sparse_homogeneous_us_0 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_0\sparse_homogeneous_us_0.mat');
sparse_homogeneous_us_0point00005 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_0point00005\sparse_homogeneous_us_0point00005.mat');
sparse_homogeneous_us_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_0point0001\sparse_homogeneous_us_0point0001.mat');
sparse_homogeneous_us_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_0point001\sparse_homogeneous_us_0point001.mat');
sparse_homogeneous_us_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_0point01\sparse_homogeneous_us_0point01.mat');
sparse_homogeneous_us_0point1 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_0point1\sparse_homogeneous_us_0point1.mat');
sparse_homogeneous_us_1 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_1\sparse_homogeneous_us_1.mat');
sparse_homogeneous_us_2 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_2\sparse_homogeneous_us_2.mat');

colmap = [255,255,204
199,233,180
127,205,187
65,182,196
29,145,192
34,94,168
12,44,132]/255;

sparse_initial_cell_number = sparse_homogeneous_us_0.live_cells(1);

figure
hold on 
plot(sparse_homogeneous_us_0.live_cells/sparse_initial_cell_number*100,'Color',colmap(1,:),'LineWidth',1)
plot(sparse_homogeneous_us_0point00005.live_cells/sparse_initial_cell_number*100,'Color',colmap(2,:),'LineWidth',1)
plot(sparse_homogeneous_us_0point0001.live_cells/sparse_initial_cell_number*100,'Color',colmap(3,:),'LineWidth',1)
plot(sparse_homogeneous_us_0point001.live_cells/sparse_initial_cell_number*100,'Color',colmap(4,:),'LineWidth',1)
plot(sparse_homogeneous_us_0point01.live_cells/sparse_initial_cell_number*100,'Color',colmap(5,:),'LineWidth',1)
plot(sparse_homogeneous_us_0point1.live_cells/sparse_initial_cell_number*100,'Color',colmap(6,:),'LineWidth',1)
plot(sparse_homogeneous_us_1.live_cells/sparse_initial_cell_number*100,'Color',colmap(6,:),'LineWidth',1)
legend('u_s = 0','u_s = 0.00005','u_s = 0.0001','u_s = 0.001','u_s = 0.01','u_s = 0.1','u_s = 1')


figure
hold on 
plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1],[sparse_homogeneous_us_0.live_cells(end),...
    sparse_homogeneous_us_0point00005.live_cells(end),...
    sparse_homogeneous_us_0point0001.live_cells(end),...
    sparse_homogeneous_us_0point001.live_cells(end),...
    sparse_homogeneous_us_0point01.live_cells(end),...
    sparse_homogeneous_us_0point1.live_cells(end),...
    sparse_homogeneous_us_1.live_cells(end)]/sparse_initial_cell_number*100,':','LineWidth',1)
plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1,2],[sparse_homogeneous_us_0.live_cells(end),...
    sparse_homogeneous_us_0point00005.live_cells(end),...
    sparse_homogeneous_us_0point0001.live_cells(end),...
    sparse_homogeneous_us_0point001.live_cells(end),...
    sparse_homogeneous_us_0point01.live_cells(end),...
    sparse_homogeneous_us_0point1.live_cells(end),...
    sparse_homogeneous_us_1.live_cells(end),...
    sparse_homogeneous_us_2.live_cells(end)]/sparse_initial_cell_number*100,'o','LineWidth',8,'MarkerSize',7)
set(gca,'xscale','log')

figure
hold on 
b = bar([sparse_homogeneous_us_0.infiltration(3,:);...
    sparse_homogeneous_us_0point00005.infiltration(3,:);...
    sparse_homogeneous_us_0point0001.infiltration(3,:);...
    sparse_homogeneous_us_0point001.infiltration(3,:);...
    sparse_homogeneous_us_0point01.infiltration(3,:);...
    sparse_homogeneous_us_0point1.infiltration(3,:);...
    sparse_homogeneous_us_1.infiltration(3,:)]','FaceColor','flat','EdgeColor',[0.9 0.9 0.9]);
b(1).CData = colmap(1,:);
b(2).CData = colmap(2,:);
b(3).CData = colmap(3,:);
b(4).CData = colmap(4,:);
b(5).CData = colmap(5,:);
b(6).CData = colmap(6,:);
b(7).CData = colmap(7,:);
set(gca,'FontSize',18)
xlim([0 12])
ylabel('Total virions')
xlabel('\mu m from periphery')
set(gca,'Xtick',linspace(1,16,16),'Xticklabel',{'0','50','100','150','200','250','300','350','400','450','500','550','600','650','700','750'})
legend('u_s = 0','u_s = 0.00005','u_s = 0.0001','u_s = 0.001','u_s = 0.01','u_s = 0.1','u_s = 1')
colormap(colmap)
c = colorbar;
set(c,'Ticks',linspace(0,1,7),'TickLabels',{'0','0.00005','0.0001','0.001','0.01','0.1','1'})

%%

figure
hold on 
plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1,2],[dense_homogeneous_us_0.live_cells(end),...
    dense_homogeneous_us_0point00005.live_cells(end),...
    dense_homogeneous_us_0point0001.live_cells(end),...
    dense_homogeneous_us_0point001.live_cells(end),...
    dense_homogeneous_us_0point01.live_cells(end),...
    dense_homogeneous_us_0point1.live_cells(end),...
    dense_homogeneous_us_1.live_cells(end),...
    dense_homogeneous_us_2.live_cells(end)]/dense_initial_cell_number*100,':','LineWidth',2)
l1 = plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1, 2],[dense_homogeneous_us_0.live_cells(end),...
    dense_homogeneous_us_0point00005.live_cells(end),...
    dense_homogeneous_us_0point0001.live_cells(end),...
    dense_homogeneous_us_0point001.live_cells(end),...
    dense_homogeneous_us_0point01.live_cells(end),...
    dense_homogeneous_us_0point1.live_cells(end),...
    dense_homogeneous_us_1.live_cells(end),...
    dense_homogeneous_us_2.live_cells(end)]/dense_initial_cell_number*100,'o','LineWidth',8,'MarkerSize',7)
plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1, 2],[sparse_homogeneous_us_0.live_cells(end),...
    sparse_homogeneous_us_0point00005.live_cells(end),...
    sparse_homogeneous_us_0point0001.live_cells(end),...
    sparse_homogeneous_us_0point001.live_cells(end),...
    sparse_homogeneous_us_0point01.live_cells(end),...
    sparse_homogeneous_us_0point1.live_cells(end),...
    sparse_homogeneous_us_1.live_cells(end),...
    sparse_homogeneous_us_2.live_cells(end)]/sparse_initial_cell_number*100,':','LineWidth',2)
l2 = plot([1e-10,0.00005,0.0001,0.001,0.01, 0.1, 1, 2],[sparse_homogeneous_us_0.live_cells(end),...
    sparse_homogeneous_us_0point00005.live_cells(end),...
    sparse_homogeneous_us_0point0001.live_cells(end),...
    sparse_homogeneous_us_0point001.live_cells(end),...
    sparse_homogeneous_us_0point01.live_cells(end),...
    sparse_homogeneous_us_0point1.live_cells(end),...
    sparse_homogeneous_us_1.live_cells(end),...
    sparse_homogeneous_us_2.live_cells(end)]/sparse_initial_cell_number*100,'o','LineWidth',8,'MarkerSize',7)
set(gca,'xscale','log')
xlabel('Stroma uptake rate, u_s')
ylabel('% Fragment remaining')
set(gca,'FontSize',18)
legend([l1 l2],{'Dense','Sparse'})


%% ------------------------------------------------------------------------------------------------------------
sparse_homogeneous_R_0point5 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\relativeuptake_0point5\sparse_homogeneous_R_0point5.mat');
sparse_homogeneous_R_1point5 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\relativeuptake_1point5\sparse_homogeneous_R_1point5.mat');
sparse_homogeneous_R_4 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\relativeuptake_4\sparse_homogeneous_R_4.mat');
sparse_homogeneous_R_10 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\relativeuptake_10\sparse_homogeneous_R_10.mat');
dense_homogeneous_R_0point5 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\relativeuptake_0point5\dense_homogeneous_R_0point5.mat');
dense_homogeneous_R_1point5 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\relativeuptake_1point5\dense_homogeneous_R_1point5.mat');
dense_homogeneous_R_4 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\relativeuptake_4\dense_homogeneous_R_4.mat');
dense_homogeneous_R_10 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\relativeuptake_10\dense_homogeneous_R_10.mat');



figure
hold on 
yyaxis left
plot([0 1 2 3],[dense_homogeneous_R_0point5.live_cells(end),...
    dense_homogeneous_R_1point5.live_cells(end),...
    dense_homogeneous_R_4.live_cells(end),...
    dense_homogeneous_R_10.live_cells(end)]/dense_initial_cell_number*100,':','LineWidth',2)
l1 = plot([0 1 2 3],[dense_homogeneous_R_0point5.live_cells(end),...
    dense_homogeneous_R_1point5.live_cells(end),...
    dense_homogeneous_R_4.live_cells(end),...
    dense_homogeneous_R_10.live_cells(end)]/dense_initial_cell_number*100,'o','LineWidth',8,'MarkerSize',7)
ylabel('% Fragment remaining')
yyaxis right
plot([0 1 2 3],[sparse_homogeneous_R_0point5.live_cells(end),...
    sparse_homogeneous_R_1point5.live_cells(end),...
    sparse_homogeneous_R_4.live_cells(end),...
    sparse_homogeneous_R_10.live_cells(end)]/sparse_initial_cell_number*100,':','LineWidth',2)
l2 = plot([0 1 2 3],[sparse_homogeneous_R_0point5.live_cells(end),...
    sparse_homogeneous_R_1point5.live_cells(end),...
    sparse_homogeneous_R_4.live_cells(end),...
    sparse_homogeneous_R_10.live_cells(end)]/sparse_initial_cell_number*100,'o','LineWidth',8,'MarkerSize',7)
xlabel('Relative uptake of cells, R')
ylabel('% Fragment remaining')
set(gca,'FontSize',18)
legend([l1 l2],{'Dense','Sparse'})
set(gca,'XTick',[0 1 2 3],'XTickLabels',{'0.5','1.5','4','10'})


%% ------------------------------------------------------------------------------------------------------------
dense_heterogeneous_us_sig_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneity_us_0point0001\dense_heterogeneous_us_sig_0point0001.mat');
dense_heterogeneous_us_sig_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneity_us_0point001\dense_heterogeneous_us_sig_0point001.mat');
dense_heterogeneous_us_sig_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneity_us_0point01\dense_heterogeneous_us_sig_0point01.mat');

dense_heterogeneous_rep_sig_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneous_rep_0point0001\dense_heterogeneous_rep_sig_0point0001.mat');
dense_heterogeneous_rep_sig_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneous_rep_0point001\dense_heterogeneous_rep_sig_0point001.mat');
dense_heterogeneous_rep_sig_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneous_rep_0point01\dense_heterogeneous_rep_sig_0point01.mat');

dense_heterogeneous_ug_sig_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneous_ug_0point00001\dense_heterogeneous_ug_sig_0point0001.mat');
dense_heterogeneous_ug_sig_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneous_ug_0point0001\dense_heterogeneous_ug_sig_0point001.mat');
dense_heterogeneous_ug_sig_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\heterogeneous_ug_0point001\dense_heterogeneous_ug_sig_0point01.mat');

dense_homogeneous_us_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\dense\us_0point01\dense_homogeneous_us_0point01.mat');

sparse_heterogeneous_rep_sig_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_rep_0poin0001\sparse_heterogeneous_rep_sig_0point0001.mat');
sparse_heterogeneous_rep_sig_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_rep_0poin001\sparse_heterogeneous_rep_sig_0point001.mat');
sparse_heterogeneous_rep_sig_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_rep_0poin01\sparse_heterogeneous_rep_sig_0point01.mat');

sparse_heterogeneous_ug_sig_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_ug_0poin00001\sparse_heterogeneous_ug_sig_0point0001.mat');
sparse_heterogeneous_ug_sig_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_ug_0point0001\sparse_heterogeneous_ug_sig_0point001.mat');
sparse_heterogeneous_ug_sig_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_ug_0point001\sparse_heterogeneous_ug_sig_0point01.mat');

sparse_heterogeneous_us_sig_0point0001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_us_0point0001\sparse_heterogeneous_us_sig_0point0001.mat');
sparse_heterogeneous_us_sig_0point001 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_us_0point001\sparse_heterogeneous_us_sig_0point001.mat');
sparse_heterogeneous_us_sig_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\heterogeneity_us_0point01\sparse_heterogeneous_us_sig_0point01.mat');

sparse_homogeneous_us_0point01 = load('C:\Users\adria\PhysiCell_V.1.6.0 GBM-OV project\PhysiCell-GBM-OV project\matlab\sparse\us_0point01\sparse_homogeneous_us_0point01.mat');


figure
hold on 
b=bar([dense_homogeneous_us_0point01.live_cells(end),...
    dense_heterogeneous_us_sig_0point0001.live_cells(end),...
    dense_heterogeneous_us_sig_0point001.live_cells(end),...
    dense_heterogeneous_us_sig_0point01.live_cells(end);...
    dense_homogeneous_us_0point01.live_cells(end),...
    dense_heterogeneous_ug_sig_0point0001.live_cells(end),...
    dense_heterogeneous_ug_sig_0point001.live_cells(end),...
    dense_heterogeneous_ug_sig_0point01.live_cells(end);...
    dense_homogeneous_us_0point01.live_cells(end),...
    dense_heterogeneous_rep_sig_0point0001.live_cells(end),...
    dense_heterogeneous_rep_sig_0point001.live_cells(end),...
    dense_heterogeneous_rep_sig_0point01.live_cells(end)]/dense_initial_cell_number*100,'FaceColor','flat','EdgeColor',[0.9 0.9 0.9])
ylabel('% Fragment remaining')
set(gca,'FontSize',18)
set(gca,'XTick',[1 2 3],'XTickLabels',{'u_s','u_g','\nu'})
legend('Homogeneous','\sigma=0.0001','\sigma=0.001','\sigma=0.01')
b(1).CData = [253,184,99]/255;
b(2).CData = [178,171,210]/255;
b(3).CData = [128,115,172]/255;
b(4).CData = [84,39,136]/255;

figure
hold on 
b=bar([sparse_homogeneous_us_0point01.live_cells(end),...
    sparse_heterogeneous_us_sig_0point0001.live_cells(end),...
    sparse_heterogeneous_us_sig_0point001.live_cells(end),...
    sparse_heterogeneous_us_sig_0point01.live_cells(end);...
    sparse_homogeneous_us_0point01.live_cells(end),...
    sparse_heterogeneous_ug_sig_0point0001.live_cells(end),...
    sparse_heterogeneous_ug_sig_0point001.live_cells(end),...
    sparse_heterogeneous_ug_sig_0point01.live_cells(end);...
    sparse_homogeneous_us_0point01.live_cells(end),...
    sparse_heterogeneous_rep_sig_0point0001.live_cells(end),...
    sparse_heterogeneous_rep_sig_0point001.live_cells(end),...
    sparse_heterogeneous_rep_sig_0point01.live_cells(end)]/sparse_initial_cell_number*100,'FaceColor','flat','EdgeColor',[0.9 0.9 0.9])
ylabel('% Fragment remaining')
set(gca,'FontSize',18)
set(gca,'XTick',[1 2 3],'XTickLabels',{'u_s','u_g','\nu'})
legend('Homogeneous','\sigma=0.0001','\sigma=0.001','\sigma=0.01')
b(1).CData = [253,184,99]/255;
b(2).CData = [178,171,210]/255;
b(3).CData = [128,115,172]/255;
b(4).CData = [84,39,136]/255;

figure
hold on 
b=bar([dense_homogeneous_us_0point01.infected_cells(end),...
    dense_heterogeneous_us_sig_0point0001.infected_cells(end),...
    dense_heterogeneous_us_sig_0point001.infected_cells(end),...
    dense_heterogeneous_us_sig_0point01.infected_cells(end);...
    dense_homogeneous_us_0point01.infected_cells(end),...
    dense_heterogeneous_ug_sig_0point0001.infected_cells(end),...
    dense_heterogeneous_ug_sig_0point001.infected_cells(end),...
    dense_heterogeneous_ug_sig_0point01.infected_cells(end);...
    dense_homogeneous_us_0point01.infected_cells(end),...
    dense_heterogeneous_rep_sig_0point0001.infected_cells(end),...
    dense_heterogeneous_rep_sig_0point001.infected_cells(end),...
    dense_heterogeneous_rep_sig_0point01.infected_cells(end)],'FaceColor','flat','EdgeColor',[0.9 0.9 0.9])
ylabel('No. infected cells')
set(gca,'FontSize',18)
set(gca,'XTick',[1 2 3],'XTickLabels',{'u_s','u_g','\nu'})
legend('Homogeneous','\sigma=0.0001','\sigma=0.001','\sigma=0.01')
b(1).CData = [253,184,99]/255;
b(2).CData = [178,171,210]/255;
b(3).CData = [128,115,172]/255;
b(4).CData = [84,39,136]/255;

figure
hold on 
b=bar([sparse_homogeneous_us_0point01.infected_cells(end),...
    sparse_heterogeneous_us_sig_0point0001.infected_cells(end),...
    sparse_heterogeneous_us_sig_0point001.infected_cells(end),...
    sparse_heterogeneous_us_sig_0point01.infected_cells(end);...
    sparse_homogeneous_us_0point01.infected_cells(end),...
    sparse_heterogeneous_ug_sig_0point0001.infected_cells(end),...
    sparse_heterogeneous_ug_sig_0point001.infected_cells(end),...
    sparse_heterogeneous_ug_sig_0point01.infected_cells(end);...
    sparse_homogeneous_us_0point01.infected_cells(end),...
    sparse_heterogeneous_rep_sig_0point0001.infected_cells(end),...
    sparse_heterogeneous_rep_sig_0point001.infected_cells(end),...
    sparse_heterogeneous_rep_sig_0point01.infected_cells(end)],'FaceColor','flat','EdgeColor',[0.9 0.9 0.9])
b(1).CData = [253,184,99]/255;
b(2).CData = [178,171,210]/255;
b(3).CData = [128,115,172]/255;
b(4).CData = [84,39,136]/255;
ylabel('No. infected cells')
set(gca,'FontSize',18)
set(gca,'XTick',[1 2 3],'XTickLabels',{'u_s','u_g','\nu'})
legend('Homogeneous','\sigma=0.0001','\sigma=0.001','\sigma=0.01')





